[build]
 command = "hugo"
 publish = "public"


[[plugins]]
package = "@netlify/plugin-functions-install-core"

[functions]
 directory = "netlify/functions"

[build.environment]
 ONESIGNAL_API_KEY = "MWUzNDYzNWItMmUzMi00NjFiLThlMzEtNzE2MmFkZmQ2MDY5"
 ONESIGNAL_APP_ID = "f4992cb9-d32a-419b-a018-efcec04673c4"
 URL = "https://entrepreneurs-guide.netlify.app/"

[build.post-processing]
 commands= [
    "curl -X POST -d '{}' ${URL}/.netlify/functions/sendNotifications"
 ]